/**
 * @file Image loading for the game client.
 *
 * Resources are looked up in the manifest served by `/api/resources` (so a
 * sheet may be an SVG generated by the engine or a PNG imported by the
 * creator). Each image is decoded once and copied into a canvas at its native
 * size: drawing from a bitmap canvas is much faster than drawing an SVG image
 * every frame, and it freezes the rasterisation so pixels stay crisp.
 *
 * Converted resources: images in an older layout (legacy autotiles and
 * tilesets, 16 px chipsets, character and face sheets) are composed into
 * standard sheets from their layout table (`shared/conversions.ts`). A tileset
 * references a converted sheet with a virtual name `<image>~<slot>`; 16 px
 * character and face sheets are converted automatically under their own name.
 */
import { conversionFor, parseVirtualName, type SheetLayout } from '../../shared/conversions.js';

/** Manifest entry (subset used by the client). */
export interface ResourceEntry {
  id: string;
  kind: string;
  name: string;
  url: string;
  hash: string;
  format: string;
  width: number | null;
  height: number | null;
}

/** A decoded image ready to draw. */
export type Bitmap = HTMLCanvasElement;

/** Loads and caches images by resource id (`kind/name`). */
export class AssetStore {
  private manifest = new Map<string, ResourceEntry>();
  private readonly images = new Map<string, Promise<Bitmap | null>>();

  /** Downloads the resource manifest. */
  async init(): Promise<void> {
    const res = await fetch('/api/resources', { credentials: 'same-origin' });
    if (!res.ok) throw new Error(`manifest: HTTP ${res.status}`);
    const body = (await res.json()) as { resources: ResourceEntry[] };
    this.manifest = new Map(body.resources.map((r) => [r.id, r]));
  }

  /** Tells whether a resource exists. */
  has(kind: string, name: string): boolean {
    return this.manifest.has(`${kind}/${name}`);
  }

  /** URL of a resource (with a cache-busting hash), or `null`. */
  url(kind: string, name: string): string | null {
    const entry = this.manifest.get(`${kind}/${name}`);
    return entry ? `${entry.url}?v=${entry.hash}` : null;
  }

  /**
   * Loads an image as a bitmap canvas. Missing or broken images resolve to `null`
   * (the renderer simply skips them).
   * @param kind - Resource folder (e.g. `tilesets`).
   * @param name - File name without extension.
   */
  image(kind: string, name: string): Promise<Bitmap | null> {
    const id = `${kind}/${name}`;
    let pending = this.images.get(id);
    if (!pending) {
      pending = this.load(kind, name);
      this.images.set(id, pending);
    }
    return pending;
  }

  private async load(kind: string, name: string): Promise<Bitmap | null> {
    const virtual = parseVirtualName(name);
    const entry = this.manifest.get(`${kind}/${virtual ? virtual.image : name}`);
    if (!entry) return null;
    const bitmap = await loadBitmap(`${entry.url}?v=${entry.hash}`);
    if (!bitmap) return null;
    const layouts = conversionFor(entry.format, bitmap.width, bitmap.height);
    if (!layouts) return bitmap;
    // Plain names of convertible character/face sheets use their first layout.
    const layout = layouts[virtual ? virtual.slot : '0'];
    return layout ? composeSheet(bitmap, layout) : virtual ? null : bitmap;
  }
}

/**
 * Builds a standard sheet from an original image and its layout table.
 * @param source - Original image.
 * @param layout - Copy operations.
 */
export function composeSheet(source: Bitmap, layout: SheetLayout): Bitmap {
  const canvas = document.createElement('canvas');
  canvas.width = layout.width;
  canvas.height = layout.height;
  const ctx = canvas.getContext('2d')!;
  ctx.imageSmoothingEnabled = false;
  for (const op of layout.ops) ctx.drawImage(source, op.sx, op.sy, op.sw, op.sh, op.dx, op.dy, op.dw, op.dh);
  return canvas;
}

/**
 * Decodes an image URL into a canvas of the same size.
 * @param url - Image URL.
 */
export async function loadBitmap(url: string): Promise<Bitmap | null> {
  const img = new Image();
  img.decoding = 'async';
  img.src = url;
  try {
    await img.decode();
  } catch {
    return null;
  }
  const canvas = document.createElement('canvas');
  canvas.width = img.naturalWidth;
  canvas.height = img.naturalHeight;
  const ctx = canvas.getContext('2d');
  if (!ctx) return null;
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(img, 0, 0);
  return canvas;
}
